[package]
name = 'ggtypst'
publish = false
version = '0.1.1'
edition = '2024'
rust-version = '1.92'

[lib]
crate-type = ['staticlib']
name = 'ggtypst'

[dependencies]
extendr-api = '0.9.0'
mitex = "0.2.4"
typst = "0.15.0"
typst-kit = { version = "0.15.0", features = [
    "embedded-fonts",
    "scan-fonts",
], default-features = false }
typst-layout = "0.15.0"
typst-svg = "0.15.0"

[lints.rust]
warnings = "deny"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

[profile.release]
lto = true
opt-level = "z"
strip = true
codegen-units = 1
