# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ggtypst_wrappers", use_symbols = TRUE, package_name = "ggtypst")

#' @usage NULL
#' @useDynLib ggtypst, .registration = TRUE
NULL

#' Return raw SVG bytes and dimensions for the given Typst input text.
#' @param text The Typst input text to render.
#' @export
typst_svg <- function(text) .Call(wrap__typst_svg, text)


# nolint end
