# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ggtypst_wrappers", use_symbols = TRUE, package_name = "ggtypst")

#' @usage NULL
#' @useDynLib ggtypst, .registration = TRUE
NULL

rs_typst_svg <- function(typst_code) .Call(wrap__rs_typst_svg, typst_code)

rs_convert_latex_to_typst <- function(latex_code) .Call(wrap__rs_convert_latex_to_typst, latex_code)

rs_mitex_alias_prelude <- function() .Call(wrap__rs_mitex_alias_prelude)


# nolint end
