# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ggtypst_wrappers", use_symbols = TRUE, package_name = "ggtypst")

#' @usage NULL
#' @useDynLib ggtypst, .registration = TRUE
NULL

typst_svg_impl <- function(text) .Call(wrap__typst_svg_impl, text)


# nolint end
